import os
import wave
import shutil
import pytest
import numpy as np
from nemantix.core import Toolset
from nemantix.stl.audio_processor.base import AudioProcessorToolset

# Define real paths relative to this test file
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_DIR = os.path.join(BASE_DIR, "test_data")
OUTPUT_DIR = os.path.join(BASE_DIR, "test_output")

# Real files that will be generated
REAL_WAV = os.path.join(INPUT_DIR, "sample.wav")
CORRUPT_WAV = os.path.join(INPUT_DIR, "corrupt.wav")


@pytest.fixture(scope="session", autouse=True)
def setup_real_files():
    """Creates directories and physically generates real audio files before running tests."""
    os.makedirs(INPUT_DIR, exist_ok=True)
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Create a real 1-second WAV file (silence)
    with wave.open(REAL_WAV, "w") as wav_file:
        wav_file.setnchannels(2)  # Stereo
        wav_file.setsampwidth(2)  # 2 bytes per sample (16-bit)
        wav_file.setframerate(44100)  # 44.1 kHz
        # Write exactly 1 second of silence
        wav_file.writeframes(b"\x00" * (44100 * 2 * 2))

    # Create a corrupt audio file (plain text only)
    with open(CORRUPT_WAV, "w", encoding="utf-8") as f:
        f.write("This is not a real audio file, it will make FFmpeg fail.")

    yield  # Pytest executes all tests here

    # Cleanup the folders after the tests end
    shutil.rmtree(INPUT_DIR, ignore_errors=True)
    shutil.rmtree(OUTPUT_DIR, ignore_errors=True)


@pytest.fixture(autouse=True)
def clean_output_dir():
    """Clears the output directory before each test to avoid false positives."""
    if os.path.exists(OUTPUT_DIR):
        for file_name in os.listdir(OUTPUT_DIR):
            file_path = os.path.join(OUTPUT_DIR, file_name)
            if os.path.isfile(file_path):
                os.unlink(file_path)  # Delete the file generated by the previous test
    yield


class TestAudioToolset:
    # --- Initialization ---

    def test_init_creates_directory(self):
        """Test that the working directory is handled correctly."""
        test_dir = os.path.join(BASE_DIR, "temp_init_dir")
        if os.path.exists(test_dir):
            shutil.rmtree(test_dir)

        AudioProcessorToolset(working_directory=test_dir)
        assert os.path.exists(test_dir)
        shutil.rmtree(test_dir)  # Immediate cleanup

    # --- Metadata & Info ---

    def test_get_audio_info_success(self):
        """Test retrieving metadata from a real audio file."""
        ts_info = Toolset.get_tool(
            tool_name="AudioProcessorToolset.get_audio_info",
            instance_args=(OUTPUT_DIR,),
        )

        result = ts_info(REAL_WAV)

        assert "1.00s" in result  # We know it lasts exactly 1 second
        assert "44100" in result  # Sample rate
        assert "Channels: 2" in result

    def test_get_audio_info_file_not_found(self):
        """Test error when file is missing."""
        ts_info = Toolset.get_tool(
            tool_name="AudioProcessorToolset.get_audio_info",
            instance_args=(OUTPUT_DIR,),
        )

        missing_file = os.path.join(INPUT_DIR, "missing_ghost_file.mp3")
        result = ts_info(missing_file)
        assert "Error: File" in result and "not found" in result

    # --- Format Conversion ---

    def test_convert_format(self):
        """Test converting audio format from WAV to MP3 using a real file."""
        ts_convert = Toolset.get_tool(
            tool_name="AudioProcessorToolset.convert_format",
            instance_args=(OUTPUT_DIR,),
        )

        result = ts_convert(REAL_WAV, output_format="mp3")

        assert "mp3" in result

        output_files = [f for f in os.listdir(OUTPUT_DIR) if f.endswith(".mp3")]
        assert len(output_files) == 1  # Ensure exactly 1 file was created

    # --- Trimming ---

    def test_trim_audio(self):
        """Test trimming a real audio segment."""
        ts_trim = Toolset.get_tool(
            tool_name="AudioProcessorToolset.trim_audio", instance_args=(OUTPUT_DIR,)
        )

        # Trim the 1-second file in half
        result = ts_trim(REAL_WAV, start_time=0.0, end_time=0.5)

        assert "Trimmed audio" in result

        output_files = [f for f in os.listdir(OUTPUT_DIR)]
        assert len(output_files) == 1

    # --- Volume Adjustment ---

    def test_adjust_volume(self):
        """Test actual volume scaling on a real file."""
        ts_volume = Toolset.get_tool(
            tool_name="AudioProcessorToolset.adjust_volume", instance_args=(OUTPUT_DIR,)
        )

        result = ts_volume(REAL_WAV, volume_factor=2.0)

        assert "Volume scaled" in result

        output_files = [f for f in os.listdir(OUTPUT_DIR)]
        assert len(output_files) == 1

    # --- Merging ---

    def test_merge_audios(self):
        """Test concatenating the real file with itself."""
        ts_merge = Toolset.get_tool(
            tool_name="AudioProcessorToolset.merge_audios", instance_args=(OUTPUT_DIR,)
        )

        files_to_merge = [REAL_WAV, REAL_WAV]
        result = ts_merge(files_to_merge)

        assert "Merged 2 files" in result

        output_files = [f for f in os.listdir(OUTPUT_DIR)]
        assert len(output_files) == 1

    # --- Decoding to NumPy ---

    def test_decode_audio(self):
        """Test decoding an actual audio file to a NumPy array."""
        ts_decode = Toolset.get_tool(
            tool_name="AudioProcessorToolset.decode_audio", instance_args=(OUTPUT_DIR,)
        )

        result = ts_decode(REAL_WAV, start_time=0, end_time=0.5)

        assert "decoded to NumPy" in result

        output_npy = [f for f in os.listdir(OUTPUT_DIR) if f.endswith(".npy")]
        assert len(output_npy) == 1

        # Extra verification: attempt to load the created numpy array
        loaded_array = np.load(os.path.join(OUTPUT_DIR, output_npy[0]))
        assert loaded_array.shape[0] > 0

    # --- Exception Handling ---

    def test_generic_exception(self):
        """Test that internal MoviePy/FFmpeg errors are caught on invalid files."""
        ts_info = Toolset.get_tool(
            tool_name="AudioProcessorToolset.get_audio_info",
            instance_args=(OUTPUT_DIR,),
        )

        result = ts_info(CORRUPT_WAV)

        assert "Error reading audio info" in result
