import os
import json
import pytest
from nemantix.core import Toolset
from nemantix.stl.email_operation.base import EmailToolset

# Define paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
REAL_CONFIG_PATH = os.path.join(BASE_DIR, "email_config.json")
DUMMY_CONFIG_PATH = os.path.join(BASE_DIR, "dummy_config.json")


@pytest.fixture(scope="session", autouse=True)
def setup_dummy_config():
    """Creates a dummy configuration file to test initialization."""
    with open(DUMMY_CONFIG_PATH, "w", encoding="utf-8") as f:
        json.dump(
            {
                "email_user": "dummy@test.com",
                "email_password": "dummy_password",
                "smtp_port": 587,
            },
            f,
        )
    yield
    # Cleanup at the end of tests
    if os.path.exists(DUMMY_CONFIG_PATH):
        os.remove(DUMMY_CONFIG_PATH)


@pytest.fixture
def real_credentials():
    """
    Loads real credentials. If the file does not exist, skips the live test.
    Returns a tuple containing (email_user, email_password, config_dict).
    """
    if not os.path.exists(REAL_CONFIG_PATH):
        pytest.skip(f"Missing {REAL_CONFIG_PATH} file. Skipping live email test.")

    with open(REAL_CONFIG_PATH, "r", encoding="utf-8") as f:
        config = json.load(f)

    user = config.get("email_user")
    pwd = config.get("email_password")

    if not user or not pwd:
        pytest.skip("Missing credentials in the real JSON file. Skipping test.")

    return user, pwd, config


class TestEmailToolsetInit:
    def test_init_defaults(self):
        """Test initialization with default servers."""
        ts = EmailToolset(email_user="u", email_password="p")
        assert ts.smtp_server == "smtp.gmail.com"
        assert ts.smtp_port == 465

    def test_from_config_success(self):
        """Test loading configuration from a valid JSON file."""
        # Uses the DUMMY file just generated by the fixture
        ts = EmailToolset.from_config(DUMMY_CONFIG_PATH)
        assert ts.email_user == "dummy@test.com"
        assert ts.smtp_port == 587

    def test_from_config_file_not_found(self):
        """Test error when config file is missing."""
        with pytest.raises(FileNotFoundError):
            EmailToolset.from_config("missing_ghost_file.json")


@pytest.mark.external
class TestEmailOperations:
    # --- Live Sending Tests ---

    def test_send_email_success(self, real_credentials):
        """Test actual email sending (sending to ourselves)."""
        user, pwd, config = real_credentials

        # Pass positional parameters extracted from config to instance_args
        ts_send = Toolset.get_tool(
            tool_name="EmailToolset.send_email",
            instance_args=(
                user,
                pwd,
                config.get("smtp_server", "smtp.gmail.com"),
                config.get("smtp_port", 465),
            ),
        )

        # Send the email to your own mailbox to verify it works
        result = ts_send(
            recipient=user,
            subject="Pytest Send Test",
            body="This is a real email sent from automated tests (without mocks).",
        )

        assert "Success" in result

    # --- Live Reading Tests ---

    def test_read_emails_success(self, real_credentials):
        """Test actual reading of the latest emails via IMAP."""
        user, pwd, config = real_credentials

        ts_read = Toolset.get_tool(
            tool_name="EmailToolset.read_emails",
            instance_args=(
                user,
                pwd,
                config.get("smtp_server", "smtp.gmail.com"),
                config.get("smtp_port", 465),
                config.get("imap_server", "imap.gmail.com"),
                config.get("imap_port", 993),
            ),
        )

        # Reads the last 2 emails
        results = ts_read(limit=2)

        # General assertions: since we don't know what's in your mailbox,
        # we verify that the network operation succeeded by returning a list.
        assert isinstance(results, list)

        # If the mailbox is not empty, verify the structure of the extracted data
        if len(results) > 0 and "error" not in results[0]:
            assert "from" in results[0]
            assert "subject" in results[0]
            assert "body_preview" in results[0]

    def test_read_emails_invalid_folder(self, real_credentials):
        """Test attempt to read a non-existent IMAP folder."""
        user, pwd, config = real_credentials

        ts_read = Toolset.get_tool(
            tool_name="EmailToolset.read_emails", instance_args=(user, pwd)
        )

        results = ts_read(folder="NON_EXISTENT_FOLDER_XYZ")

        assert isinstance(results, list)
        assert "error" in results[0]
        assert "Could not select folder" in results[0]["error"]
