from nemantix.knowledge_base.document_structure.coordinates import Coordinates
from nemantix.knowledge_base.document_structure.document import Document
from nemantix.knowledge_base.document_structure.hierarchy import DocumentHierarchy
